version: '3'
services:
  postgres:
    image: postgres:14-alpine
    # Uncomment if you want access to DB access from Host
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=jasper
    volumes:
      - pg_data:/var/lib/postgresql/data

  jasperserver:
    image: tobe81cwb/jasperserver:8.0.2
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
    volumes:
      # Relative path on the host/volume on container
      - /jasperserver-import:/jasperserver-import
    depends_on:
      - postgres

volumes:
  pg_data:
